# ----------------------- #
# Site directory layout   #
# ----------------------- #

# The default layout like below
#(.)
# |
# +- site (the default site/blog directory).
# |   |
# |   +- config.yml (The site configuration file)
# |   |
# |   +- source (All YAML front-matter header files and some static files)
# |   |
# |   +- templates (FreeMarker template ONLY)
# |   |
# |   +- assets (All static files ONLY)
# |  
# +- (site2) another site
# |
# +- target
#     |
#     +- public
#     |    |
#     |    +- site the output directory for site
#     |    |
#     |    +- (site2) the output directory for site2
#     |
#     +- sass-cache
#     |
#     +- work



# 'site' set the root directory of your site or blog, default value is the parent directory of this file. 
# The subdirectory of 'site' are:
# 	source：        must exists, store all YAML front-matter header files.
#   templates：if not exists, then 'site/source/_templates' subdirectory, 
#					one of 'site/templates' or 'site/source/_templates' must exists.
#					store all FreeMarker template files.
#	assets:    an optional subdirectory. store all static files(JavaScripts, images, ..)
#                   in this folder will make the generate process more faster. 
# site: site

# The output directory, default value is '../target/public/${site}'. '${site}' value see above.
# destination: target/public/site

# The working directory, default value is '../target/work/${site}''.
# working_dir: target/work/site


# ----------------------- #
#      Main Configs       #
# ----------------------- #
# Default value is java.util.Locale.getDefault()
# locale: en_US
url: http://yourwebsite.com
title: My OpooPress Blog
subtitle: Just another OpooPress.com site.
author: Your Name
simple_search: http://google.com/search
description: OpooPress blogging framework is a java basesd static blog/site generator.
keywords: "OpooPress, Blog"

# Default date format is "ordinal" (resulting in 'Jun 20 2013', java date format pattern
# is 'MMM d yyyy'). You can specify a custom java date format style string here such as 'yyyy-MM-dd'
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /

# Permalink style supports variables：
# 		The fron-matter headers of post, and ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${pathToFile}, ${fileName} 
permalink: /article/${year}/${month}/${name}/
# permalink_label: "&infin;"
# permalink_label_feed: "&#9875; Permalink"

# New post file full path (in source folder), supports variables: ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}, ${format}
# Default format is 'markdown'.
new_post: article/${year}-${month}-${day}-${name}.${format}

# New page file full path (in source folder), supports variables: ${year}, ${month}, ${day}, ${hour}, ${minute}, ${second}, ${name}, ${title}, ${date}, ${format}
# Default format is 'markdown'.
new_page: ${name}.${format}

# category folder
category_dir: /category

# Define the mapping of category nicename and name.
# The categories that not defined here will be appropriate processed.
category_names: {"opoopress": "OpooPress", "blog": "Blog"}

# Category title prefix.
category_title_prefix: "Category: "

# tag directory
tag_dir: /tag

# Define the mapping of tag slug and name.
# tag_names: {}

# tag title prefix
tag_title_prefix: "Tag: "

# Posts per page on the blog index
paginate: 10          		

# Posts in the sidebar Recent Posts section
recent_posts: 5

# Posts in the bottom Related Posts section
related_posts: 5   	

# "Continue reading" link text at the bottom of excerpted articles
excerpt_link: "Read on &rarr;"  

# excerpt separator
excerpt_separator: "<!--more-->"

# Converts page and post titles to titlecase
titlecase: true

# show relative time, e.g. "1 minute ago", "4 years ago"
refreshRelativeTimes: true

# Main navigation
navs: {"Blog": "/", "Archives": "/archives/", "Sample Page": "/sample-page.html", "About": "/about/"}

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in 'site/templates/asides' or 'site/source/_templates/asides' 
# and add them to the list like 'custom_aside_name.ftl'
default_asides: [recent_posts.ftl, github.ftl, delicious.ftl, pinboard.ftl, googleplus.ftl, categories.ftl, tags.ftl]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: 
github_repo_count: 0
github_show_profile_link: false
github_skip_forks: true

# Twitter
twitter_user:
twitter_tweet_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 
googleplus_hidden: false

# Pinboard
pinboard_user: 
pinboard_count: 3

# Delicious
delicious_user: 
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Duoshuo Comments
duoshuo_short_name:
duoshuo_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:
google_analytics_tracking_domain:

# Facebook Like
facebook_like: false


# ----------------------- #
#   Deployment Settings   #
# ----------------------- #
# deploy_server: {id: my_vps_server, url: 'scp://my.vps.ip/var/www/html', user: 'ssh_username'}



#####################################################################################
## CONFIGURATION BELOW FOR DEVELOPER ONLY (Secondary development)
## If you don't understand what they are, don't change them.
#####################################################################################

# ----------------------- #
#   PlugIns Settings      #
# ----------------------- #
# plugins: 
#  - org.opoo.press.plugin.SamplePlugin


# ------------------------ #
# Default PlugIn Settings  #
# ------------------------ #
converters:
  - org.opoo.press.converter.TxtmarkMarkdownConverter
  - org.opoo.press.converter.TextilejConverter
  - org.opoo.press.converter.WikiTextMediaWikiConverter
  - org.opoo.press.converter.WikiTextTracWikiConverter
  - org.opoo.press.converter.WikiTextTWikiConverter
  - org.opoo.press.converter.WikiTextConfluenceConverter

generators:
  - org.opoo.press.generator.PaginationGenerator
  - org.opoo.press.generator.CategoryGenerator
  - org.opoo.press.generator.TagGenerator

# siteFilters:
#  - org.opoo.press.filter.FixUrlSiteFilter

# ----------------------- #
#   SlugHelper            #
# ----------------------- #
slugHelper: org.opoo.press.slug.DefaultSlugHelper

# ----------------------- #
#   Code Block Settings   #
# ----------------------- #

# Default use 'SyntaxHighlighter' as the highlighter code block processor
# http://alexgorbatchev.com/SyntaxHighlighter/
highlighter: "org.opoo.press.highlighter.SyntaxHighlighter"


# ----------------------- #
#   FreeMarker config     #
# ----------------------- #

# auto_import_templates: {"ns" : "template_name.ftl", "ns2" : "template2_name.ftl"}
# auto_include_templates: ["global_template1.ftl", "global_template2.ftl"]


# ----------------------- #
#   Debug JavaScript      #
# ----------------------- #
verbose: false